name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow.

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SVC_ACCOUNT: ${{ secrets.GCP_SVC_ACCOUNT }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/${{ secrets.GCP_SVC_ACCOUNT }}.json
  SVC_ACCOUNT_EMAIL: ${{ secrets.GCP_SVC_ACCOUNT }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
  GAR_LOCATION: ${{ vars.GCP_REGION }}
  GAR_REPOSITORY: ${{ vars.GCP_NAME }}
  CLOUD_RUN_SERVICE_NAME: 'estadistica-front' # Ej: my-awesome-app
  CLOUD_RUN_REGION: ${{ vars.GCP_REGION }}
  CR_UI_IMAGE_NAME: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.GCP_NAME }}:${{ github.sha }}

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
      - name: Verificar env
        run: |
          echo "Environment variables configured:"
          echo PROJECT_ID="$GCP_PROJECT_ID"
          echo REGION="$GAR_LOCATION"
          echo SVC_ACCOUNT="$SVC_ACCOUNT"
          echo SVC_ACCOUNT_EMAIL="$SVC_ACCOUNT_EMAIL"
          echo GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS"
          echo Repo="$GAR_REPOSITORY"
          echo Region2="$CLOUD_RUN_REGION"
          echo ""

      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GCP_SVC_ACCOUNT_CREDS }}" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
          gcloud auth activate-service-account $SVC_ACCOUNT_EMAIL --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud config set project $GCP_PROJECT_ID
          gcloud config set run/region $GAR_LOCATION

      # Opcional: Si necesitas autenticar Docker con Artifact Registry (setup-gcloud a menudo lo maneja)
      # - name: Configure Docker
      #   run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }} .
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:latest . # Opcional: tag 'latest'

      - name: Push Docker image to Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:latest # Opcional: push 'latest'
